#!/usr/bin/env python3
"""
Sprint 1 Comprehensive Test Runner
Executes all tests and generates detailed report.
"""

import subprocess
import sys
import json
from datetime import datetime
from pathlib import Path

def run_tests():
    """Run all Sprint 1 tests with detailed output."""

    report = {
        "timestamp": datetime.now().isoformat(),
        "sprint": "Sprint 1 - Visual & Geometric Upgrade",
        "phases": {}
    }

    test_files = [
        ("Unit Tests - BuildingGene", "tests/sprint1/test_building_gene.py"),
        ("Unit Tests - ShapeGenerator", "tests/sprint1/test_shape_generator.py"),
        ("Unit Tests - CompositeGenotype", "tests/sprint1/test_composite_genotype.py"),
        ("Unit Tests - SmartMagnet", "tests/sprint1/test_smart_magnet.py"),
        ("Integration Tests", "tests/sprint1/test_integration.py"),
        ("Performance Benchmarks", "tests/sprint1/test_performance.py"),
        ("Edge Case Tests", "tests/sprint1/test_edge_cases.py"),
    ]

    all_passed = True

    for name, filepath in test_files:
        print(f"\n{'='*60}")
        print(f"Running: {name}")
        print(f"{'='*60}")

        result = subprocess.run(
            [sys.executable, "-m", "pytest", filepath, "-v", "--tb=short"],
            capture_output=True,
            text=True
        )

        # Parse results
        passed = result.returncode == 0
        if not passed:
            all_passed = False

        report["phases"][name] = {
            "file": filepath,
            "passed": passed,
            "returncode": result.returncode,
            "stdout": result.stdout,
            "stderr": result.stderr
        }

        # Print output
        print(result.stdout)
        if result.stderr:
            print("STDERR:", result.stderr)

    report["all_passed"] = all_passed

    return report


def generate_markdown_report(report: dict) -> str:
    """Generate markdown report from test results."""

    md = []
    md.append("# 🧪 Sprint 1 Comprehensive Test Report")
    md.append(f"\n**Generated:** {report['timestamp']}")
    md.append(f"\n**Sprint:** {report['sprint']}")
    md.append(f"\n**Overall Status:** {'✅ ALL PASSED' if report['all_passed'] else '❌ SOME FAILED'}")

    md.append("\n---\n")
    md.append("## Summary Table\n")
    md.append("| Test Phase | Status | Details |")
    md.append("|------------|--------|---------|")

    for name, data in report["phases"].items():
        status = "✅ PASS" if data["passed"] else "❌ FAIL"
        # Count tests from output
        stdout = data["stdout"]
        passed_count = stdout.count(" PASSED")
        failed_count = stdout.count(" FAILED")
        md.append(f"| {name} | {status} | {passed_count} passed, {failed_count} failed |")

    md.append("\n---\n")

    # Detailed results for each phase
    for name, data in report["phases"].items():
        md.append(f"## {name}\n")
        md.append(f"**File:** `{data['file']}`\n")
        md.append(f"**Status:** {'✅ PASSED' if data['passed'] else '❌ FAILED'}\n")

        # Extract test names and results
        md.append("\n### Test Results\n")
        md.append("```")

        # Parse stdout for test results
        lines = data["stdout"].split("\n")
        for line in lines:
            if "PASSED" in line or "FAILED" in line or "ERROR" in line:
                md.append(line)

        md.append("```\n")

        if not data["passed"] and data["stderr"]:
            md.append("\n### Errors\n")
            md.append("```")
            md.append(data["stderr"][:2000])  # Limit error output
            md.append("```\n")

    md.append("\n---\n")
    md.append("## Performance Benchmarks\n")

    # Extract benchmark results
    if "Performance Benchmarks" in report["phases"]:
        perf_stdout = report["phases"]["Performance Benchmarks"]["stdout"]
        md.append("```")
        for line in perf_stdout.split("\n"):
            if "ms" in line or "buildings" in line or "roads" in line:
                md.append(line)
        md.append("```\n")

    md.append("\n---\n")
    md.append("## Recommendations\n")

    if report["all_passed"]:
        md.append("✅ All tests passed. Sprint 1 is ready for production.\n")
        md.append("- Proceed to Sprint 2 (Physics & Context)\n")
        md.append("- Consider adding more edge case tests for production\n")
    else:
        md.append("❌ Some tests failed. Review and fix before proceeding.\n")
        md.append("- Check failed test details above\n")
        md.append("- Fix issues before Sprint 2\n")

    md.append("\n---\n")
    md.append("*Report generated by PlanifyAI Sprint 1 Test Suite*")

    return "\n".join(md)


if __name__ == "__main__":
    print("🧪 PlanifyAI Sprint 1 Comprehensive Test Suite")
    print("=" * 60)

    # Run all tests
    report = run_tests()

    # Generate markdown report
    markdown = generate_markdown_report(report)

    # Save report
    report_path = Path("SPRINT1_TEST_REPORT.md")
    report_path.write_text(markdown)

    print(f"\n{'='*60}")
    print(f"📄 Report saved to: {report_path}")
    print(f"{'='*60}")

    # Also save JSON for programmatic access
    json_path = Path("sprint1_test_results.json")
    json_path.write_text(json.dumps(report, indent=2, default=str))
    print(f"📊 JSON data saved to: {json_path}")

    # Exit with appropriate code
    sys.exit(0 if report["all_passed"] else 1)
